package com.example.myluck.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.myluck.entity.SysAuth;
import com.example.myluck.entity.SysUser;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SysAuthMapper extends BaseMapper<SysAuth> {

    List<SysAuth> getAuthByUid(int uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int insert(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int insertSelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    SysAuth selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAuth record);
}