package com.example.myluck.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.example.myluck.entity.SysRole;
import com.example.myluck.entity.SysRoleAuth;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SysRoleAuthMapper extends BaseMapper<SysRoleAuth> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    int insert(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    SysRoleAuth selectByPrimaryKey(Integer roleAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleAuth record);
}