package com.example.myluck.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.util.Date;
@Data
public class SysAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.aid
     *
     * @mbggenerated
     */
    @TableId(type = IdType.AUTO)
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_name
     *
     * @mbggenerated
     */
    private String authName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.auth_describe
     *
     * @mbggenerated
     */
    private String authDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_auth.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;


}